name: Build Android APK (Buildozer)

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev build-essential git \
              libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev \
              libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
              pkg-config libgl1-mesa-dev libgles2-mesa-dev \
              android-sdk-platform-tools android-sdk-build-tools

      - name: Install Buildozer
        run: pip3 install buildozer==1.5.0

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-apk
          path: ./bin/*.apk
        if: success()
